# Generated by Django 5.2.4 on 2026-04-03 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
